### ISSUE TITLE
Missing enum support in the diagrams

### ISSUE THREAD

**Issue by dandelion-lowcode** [epsilonlabs/playground#1]
Enums only seem to be rendered if referenced with 'val', and literals are not displayed.

E.g., try:

- changing val to attr, or
- commenting ///////// 1 /////////

in https://eclipse.dev/epsilon/playground/?0df9c475.
 
May probably require changing src/main/resources/emfatic2plantuml.egl.

**Comment by kolovos** [comment]
Fixed in 2caf2813a7cb39721a5dfa64c70c3fc9e617406c. An example is available here: https://eclipse.dev/epsilon/playground/?5bb3cb04
